<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>96d5766a-7863-4a02-bcdc-bb3576b8b372</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SaaS.ServiceDefaults\SaaS.ServiceDefaults.csproj" />
    <ProjectReference Include="..\SaaS.Shared\SaaS.Shared.csproj" />
  </ItemGroup>

</Project>
